site_name: MOC-IoT Documentation
site_description: Internal documentation for MOC-IoT device management system
site_author: MOC-IoT Engineering Team
site_url: https://docs.moc-iot.com

repo_name: MOC-IoT/docs
repo_url: https://github.com/MOC-IoT/docs
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - navigation.footer
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: ../assets/logo.png
  favicon: ../assets/favicon.ico
  custom_dir: overrides

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mermaid2
  - git-revision-date-localized:
      enable_creation_date: true

nav:
  - Home: index.md
  - Architecture:
    - System Overview: SYSTEM_ARCHITECTURE.md
    - Data Flow: DATA_FLOW_GUIDE.md
  - API Documentation:
    - Edge Function API: api/edge-function.md
    - Fly.io CoAP Interface: api/flyio-coap.md
    - Data Schemas: api/schemas.md
  - Operations:
    - Deployment: FLYIO_SETUP.md
    - Monitoring: operations/monitoring.md
    - Troubleshooting: operations/troubleshooting.md
  - Development:
    - Local Setup: DEVELOPMENT_GUIDE.md
    - Testing: development/testing.md
    - Contributing: development/contributing.md
  - Reference:
    - Environment Variables: reference/environment.md
    - Database Schema: reference/database.md
    - Change Log: reference/changelog.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MOC-IoT
  analytics:
    provider: custom
    property: auth-check

copyright: Copyright &copy; 2025 MOC-IoT Engineering Team